### ISSUE TITLE
release 监听异常

### ISSUE THREAD

**Issue by byx2020** [gnuf0rce/github-helper#4]
先说明一下，因为我关注的github项目更新本来就很少，所以直到前两天我才注意到此插件的功能失效了，这间接导致了我无法确定此问题具体的出现时间，不过应该已经存在较长一段时间了。
已知的信息是，从群内的聊天记录看，最后一次成功推送github项目更新通知的时间为2月6日21:14，当时我使用的插件版本为1.1.5，然后从文件“github-helper-1.1.7.mirai.jar”的修改日期可知，在2月6日当天晚上23:28，我将插件的版本从1.1.5升级到了1.1.7，之后我关注的github项目有过更新，但没有再成功推送过一次通知到群内，另外，文件“mirai-core-all-2.10.0.jar”的修改日期为2月6日21:16，期间我可能还更新了mirai，所以不确定是哪个因素导致插件失效的。
发现问题后，我尝试通过删除插件配置文件和数据并重新订阅项目来解决问题，但并没有效果，然后我将插件的版本回退到了1.1.5，但还是不行，项目更新仍然没有更新推送到群内，期间我注意到插件数据文件“RepoTaskData.yml”里面的“last”除了使用指令刚订阅时更新了一次，之后没再发生过变化。
以下为插件运行环境信息：
服务器配置：2C4G
操作系统：Windows Server 2012 R2 DataCenter 64bitCN
JRE版本：OpenJDK Runtime Environment Temurin-11.0.12+7 (11.0.12+7) (build 11.0.12+7)
Java VM：OpenJDK Client VM Temurin-11.0.12+7 (11.0.12+7, mixed mode, serial gc, windows-x86)
Mirai版本：2.10.0(最新版)
插件版本：1.1.7、1.1.5
其他说明：下图为插件配置和数据文件里面的内容，这可能也许会对解决此问题有所帮助，如果大佬需要更多信息或协助，也可以让我提供
![image](https://user-images.githubusercontent.com/58938653/154524026-7049da13-8fff-4009-a95e-a696bc490aad.png)
![image](https://user-images.githubusercontent.com/58938653/154523827-46a237f5-02db-49cd-beac-9af527be8652.png)
![image](https://user-images.githubusercontent.com/58938653/154523913-41e5b20f-36de-4cad-9b15-2587d0256498.png)

**Comment by cssxsh** [comment]
为啥要截图？

**Comment by byx2020** [comment]
> 为啥要截图？

@cssxsh 方便排版，如果这样不好的话，那我把文字版也发一遍吧

GithubConfig.yml
```
# Proxy Format http://127.0.0.1:8080 or socks://127.0.0.1:1080
proxy: ''
# GitHub Token by https://github.com/settings/tokens
github_token: ''
# Subscriber Reply Message Type
reply_type: TEXT
# Http Timeout Second
timeout: 30
# 放行活跃等级（百分制）
percentage_member_join: 0
# 加群提醒
sign_member_join: 新人入群请看群公告
# with https://github-readme-stats.vercel.app/
github_readme_stats: 
  show_icons: true
  theme: tokyonight
  count_private: true
  include_all_commits: true
```
RepoTaskData.yml
```
commits: {}

issues: {}

pulls: {}

releases: 
  'RW-HPS/RW-HPS': 
    id: 'RW-HPS/RW-HPS'
    contacts: 
      - 416570727
    last: '2022-02-16T06:29:13Z'
    interval: 600000
  'mamoe/mirai': 
    id: 'mamoe/mirai'
    contacts: 
      - 416570727
    last: '2022-02-12T15:04:05.0604138Z'
    interval: 600000
```
TaskData.yml
`issues: {}
`
